classdef intrinsicsEstimationErrors
% intrinsicsEstimationErrors Object for storing standard errors of
%   estimated camera intrinsics and distortion coefficients
%
%   intrinsicsEstimationErrors properties:
%   SkewError                 - standard error of camera axes skew estimate
%   FocalLengthError          - standard error of focal length estimate
%   PrincipalPointError       - standard error of principal point estimate
%   RadialDistortionError     - standard error of radial distortion estimate
%   TangentialDistortionError - standard error of tangential distortion estimate
%
%   See also cameraCalibrationErrors, stereoCalibrationErrors

%   Copyright 2013 MathWorks, Inc.

    properties(GetAccess=public, SetAccess=private)
        % SkewError A scalar containing the standard error of the estimated
        %  camera axes skew.
        SkewError;
        
        % FocalLengthError A 2-element vector containing the standard error
        %  of the focal length in x and y.
        FocalLengthError;
        
        % PrincipalPointError A 2-element vector containing the standard
        %   error of the principal point (camera center).
        PrincipalPointError;
        
        % RadialDistortionError A 2-element or 3-element vector containing
        %   the standard error of the estimated radial distortion coefficients.
        RadialDistortionError;
        
        % TangentialDistortionError A 2-element vector containing the
        %   standard error of the estimated tangential distortion coefficients.
        TangentialDistortionError;
    end
    
    methods
        function this = intrinsicsEstimationErrors(errors)
            this.SkewError                 = errors.skew;
            this.FocalLengthError          = errors.focalLength;
            this.PrincipalPointError       = errors.principalPoint;
            this.RadialDistortionError     = errors.radialDistortion;
            this.TangentialDistortionError = errors.tangentialDistortion;
        end
        
        %------------------------------------------------------------------
        function displayErrors(this, cameraParams)
            % Display standard error of intrinsics
            frameFormat = '%-25s[%23s%25s]\n';
            entryFormat = '%8.4f +/- %-8.4f';
            
            focalLengthString{1} = sprintf(entryFormat,...
                cameraParams.FocalLength(1), ...
                this.FocalLengthError(1));
            focalLengthString{2} = sprintf(entryFormat,...
                cameraParams.FocalLength(2), ...
                this.FocalLengthError(2));
            principalPointString{1} = sprintf(entryFormat,...
                cameraParams.PrincipalPoint(1), ...
                this.PrincipalPointError(1));
            principalPointString{2} = sprintf(entryFormat,...
                cameraParams.PrincipalPoint(2), ...
                this.PrincipalPointError(2));
            radialDistortionString{1} = sprintf(entryFormat,...
                cameraParams.RadialDistortion(1), ...
                this.RadialDistortionError(1) ...
                );
            radialDistortionString{2} = sprintf(entryFormat,...
                cameraParams.RadialDistortion(2), ...
                this.RadialDistortionError(2) ...
                );            
            
            fprintf(frameFormat,...
                vision.getMessage('vision:cameraCalibrationErrors:focalLength'),...
                focalLengthString{1}, ...
                focalLengthString{2});
            
            fprintf(frameFormat,...
                vision.getMessage('vision:cameraCalibrationErrors:principalPoint'),...
                principalPointString{1}, ...
                principalPointString{2});
            
            if cameraParams.EstimateSkew
                frameFormatSkew =  '%-25s[%23s]\n';
                skewString =  sprintf(entryFormat,...
                    cameraParams.Skew, ...
                    this.SkewError);
                
                fprintf(frameFormatSkew,...
                    vision.getMessage('vision:cameraCalibrationErrors:skew'),...
                    skewString);
            end
            
            if cameraParams.NumRadialDistortionCoefficients == 2                
                fprintf(frameFormat, ...
                    vision.getMessage('vision:cameraCalibrationErrors:radialDistortion'),...
                    radialDistortionString{1}, ...
                    radialDistortionString{2});                
            else
                frameFormatRadial3 = '%-25s[%23s%25s%25s]\n';                
                radialDistortionString{3} = sprintf(entryFormat,...
                    cameraParams.RadialDistortion(3), ...
                    this.RadialDistortionError(3) ...
                    );                
                
                fprintf(frameFormatRadial3, ...
                    vision.getMessage('vision:cameraCalibrationErrors:radialDistortion'),...
                    radialDistortionString{1}, ...
                    radialDistortionString{2}, ...
                    radialDistortionString{3});                
            end
            
            if cameraParams.EstimateTangentialDistortion
                tangentialDistortionString{1} = sprintf(entryFormat,...
                    cameraParams.TangentialDistortion(1), ...
                    this.TangentialDistortionError(1));
                tangentialDistortionString{2} = sprintf(entryFormat,...
                    cameraParams.TangentialDistortion(2), ...
                    this.TangentialDistortionError(2));
                                
                fprintf(frameFormat, ...
                    vision.getMessage('vision:cameraCalibrationErrors:tangentialDistortion'),...
                    tangentialDistortionString{1}, ...
                    tangentialDistortionString{2});
            end
        end
    end
end