function libs = librarylist
% LIBRARYLIST Return list of Computer Vision System Toolbox block libraries

% Copyright 2003-2008 The MathWorks, Inc.

% Current list of libraries
libs.current = {'visionanalysis','visionconversions','visionfilter',...
                'visiongeotforms','visionmorphops','visionsinks',...
                'visionsources','visionstatistics','visiontextngfix',...
                'visiontransforms','visionutilities'};

% set of obsolete libraries slated for removal; this list is used
% by vision.internal.visionlinks
libs.toremove = {'vipobslib','vipanalysis','vipgeotforms','vipstatistics',...
                 'viptextngfix','viptransforms'};

libs.formalNames = {'Analysis & Enhancement', 'Conversions', 'Filtering', ...
                    'Geometric Transformations', 'Morphological Operations', ...
                    'Video Processing Sinks', 'Video Processing Sources', ...
                    'Statistics', 'Text & Graphics', 'Transforms',...
                    'Utilities'};

libs.formalName = 'Computer Vision System Toolbox';
