function Hd = vipstripes_filter
%MYREJECT Returns a discrete-time filter object

% Copyright 2004 The MathWorks, Inc.

%
% MATLAB File generated by MATLAB(R) 7.0 and the Signal Processing Toolbox 6.2.
%
% Generated on: 30-Mar-2004 09:39:08
%

% FIR least-squares Bandstop filter designed using the FIRLS function.

% All frequency values are normalized to 1.

N      = 30;    % Order
Fpass1 = 0.51;  % First Passband Frequency
Fstop1 = 0.6;   % First Stopband Frequency
Fstop2 = 0.7;   % Second Stopband Frequency
Fpass2 = 0.79;  % Second Passband Frequency
Wpass1 = 1;     % First Passband Weight
Wstop  = 1;     % Stopband Weight
Wpass2 = 1;     % Second Passband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass1 Fstop1 Fstop2 Fpass2 1], [1 1 0 0 1 1], ...
           [Wpass1 Wstop Wpass2]);
Hd = dfilt.dffir(b);



% [EOF]
