% MCodeGenerator provides convenience methods for generating M-code%

% Copyright 2014 The MathWorks, Inc.

classdef MCodeGenerator < handle
    properties(GetAccess=public, SetAccess=private)
        CodeString = '';
    end
    
    methods
        %--------------------------------------------------------------
        function addHeader(this, appName)
            this.CodeString = sprintf(['%% Auto-generated by ', ...
                '%s app on %s'], appName, date);
            this.addLine(['%----------------------------------------', ...
                '---------------']);
            this.addReturn();
        end
        
        %--------------------------------------------------------------
        function addReturn(this)
            this.CodeString = [this.CodeString, sprintf('\n')];
        end
        
        %--------------------------------------------------------------
        function addComment(this, commentString)
            addReturn(this);
            addLine(this, ['% ', commentString]);
        end
        
        %--------------------------------------------------------------
        function addLine(this, lineString)
            addReturn(this);
            this.CodeString = [this.CodeString lineString];
        end
    end
end