function checkOverlapRatio(range, fname, pname)
validateattributes(range, {'numeric'}, ...
    {'vector', 'numel', 2, 'real', 'finite', 'nonsparse', 'nonnegative', 'increasing', '<=', 1},...
    fname, pname);