function checkMiniBatchSize(sz, callername)
validateattributes(sz,...
    {'numeric'}, ...
    {'scalar', 'real', 'positive', 'integer', 'nonempty', 'finite', 'nonsparse'}, ...
    callername, 'MiniBatchSize');