function [points1, points2] = checkAndConvertMatchedPoints(...
    matchedPoints1, matchedPoints2, fileName, varName1, varName2)
% Checks if points are valid and consistent, and converts to x-y coordinates.

%#codegen
coder.internal.errorIf( ...
    ~isequal(class(matchedPoints1), class(matchedPoints2)), ...
    'vision:points:ptsClassMismatch', varName1, varName2);

points1 = vision.internal.inputValidation.checkAndConvertPoints(...
    matchedPoints1, fileName, varName1);
points2 = vision.internal.inputValidation.checkAndConvertPoints(...
    matchedPoints2, fileName, varName2);

coder.internal.errorIf(~isequal(size(points1), size(points2)), ...
    'vision:points:numPtsMismatch', varName1, varName2);