function mapOldMaskToCurrent = vipblksBrokenLinksMapping()
% Broken links restoration mapping for Computer Vision System Toolbox

% Copyright 2007-2015 The MathWorks, Inc.
%  

mapOldMaskToCurrent = ...
    cat(1, ...
    dspvisionMap, ... 
    vipobslibMap, ...             % obsolete library
    vipanalysisMap,...            % obsolete library
    vipmiscMap, ...
    visionanalysisMap, ...
    visionsourcesMap, ...
    visionutilitiesMap, ...
    visionconversionsMap, ...
    visiongeotformsMap, ...
    visionmorphopsMap, ...
    visionstatisticsMap, ...
    visionfilterMap, ...
    visiontextngfixMap, ...
    visionsinksMap, ...
    visiontransformsMap);

% Note: viputilities, vipgeotforms, etc. are not included in the mapping
%       since they contain blocks with names identical to the vision*
%       equivalents.  That means that if a link to an older block from
%       vip* libray is broken, it will be restored to its vision* version.
%
%       vipanalysis is an exception because it holds Trace Boundaries while
%       visionanalysis has Trace Boundary (different name).  Hence we have
%       two separate mappings for these libraries that cover Trace Boundary
%       explicitly

mapOldMaskToCurrent = cell2struct( mapOldMaskToCurrent, ...
    { 'oldMaskType','newMaskType','newBlockType','newRefBlock', ...
      'MaskNames', 'SFunctionName' }, 2);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                               %
% Block listings for individual libraries       %
%                                               %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function mapOldMaskToCurrent = dspvisionMap()
mapOldMaskToCurrent = { ...
'From Multimedia File', ...
   'From Multimedia File', ...
   'S-Function', ...
   'dspvision/From Multimedia File', ...
   { ...
    'inputFilename'; ...
    'loop'; ...
    'numPlays'; ...
    'outputStreams'; ...
    'videoDataType'; ...
    'audioDataType'; ...
    'inheritSampleTime'; ...
    'userDefinedSampleTime'; ...
    'noAudioOutput'; ...
    'isIntensityVideo'; ...
    'fourcc'; ...
    'colorVideoFormat'; ...
    'outputEOF'; ...
    'dataOrg'; ...
    'audioFrameSize'; ...
    'computeAudioFrameSize'; ...
    'outSamplingMode'; ...   
   }, ...
   'sdspwmmfi2'; ...
'To Multimedia File', ...
   'To Multimedia File', ...
   'S-Function', ...
   'dspvision/To Multimedia File', ...
   { ...
    'outputFilename'; ... 
    'streamSelection'; ... 
    'videoCompressor'; ... 
    'audioCompressor'; ... 
    'imagePorts'; ... 
    'fileType'; ... 
    'audioDatatype'; ... 
    'fourcc'; ... 
    'videoQuality'; ...
    'mj2000CompFactor';
   }, ...
   'sdspwmmfo2'; ... 
};

function mapOldMaskToCurrent = vipmiscMap()
mapOldMaskToCurrent = { ...
'Block processing dimension propagation', ...
   'Block processing dimension propagation', ...
   'S-Function', ...
   'vipmisc/Block dimension\npropagation', ...
   { ...
      'szp'; ...
      'oszp'; ...
   }, ...
   'svipblkprop'; ...
'Index generator', ...
   'Index generator', ...
   'S-Function', ...
   'vipmisc/Index generator', ...
   { ...
      'blksize'; ...
      'ovlpsize'; ...
      'tverse'; ...
      'assp'; ...
      'indexst'; ...
   }, ...
   'svipindexgenol'; ...
'Input for block processing', ...
   'Input for block processing', ...
   'SubSystem', ...
   'vipmisc/Input', ...
   { ...
      'Blocksize'; ...
      'Overlapsize'; ...
      'tverse'; ...
   }, ...
   ''; ...
'Block processing iteration counter', ...
   'Block processing iteration counter', ...
   'S-Function', ...
   'vipmisc/Iteration count', ...
   { ...
      'blksize'; ...
      'ovlpsize'; ...
   }, ...
   'svipblockprociter'; ...
'', ...
   '', ...
   'SubSystem', ...
   'vipmisc/Output', ...
   { ...
      'Blocksize'; ...
      'Overlapsize'; ...
      'tverse'; ...
   }, ...
   ''; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = vipobslibMap()
mapOldMaskToCurrent = { ...
'Read AVI File', ...
   'Read AVI File', ...
   'M-S-Function', ...
   'vipobslib/Read AVI File', ...
   { ...
      'filename'; ...
      'loopOrNot'; ...
      'numLoops'; ...
      'dataType'; ...
      'outputEOF'; ...
   }, ...
   'svipreadavifile'; ...
'Write AVI File', ...
   'Write AVI File', ...
   'M-S-Function', ...
   'vipobslib/Write AVI File', ...
   { ...
      'filename'; ...
      'inputType'; ...
      'imagePorts'; ...
   }, ...
   'svipwriteavifile'; ...
'SAD', ...
   'SAD', ...
   'S-Function', ...
   'vipobslib/SAD', ...
   { ...
      'output'; ...
      'method'; ...
      'roi'; ...
      'invalidROI'; ...
      'nearbyPel'; ...
      'nearbySize'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svip2dsad'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = vipanalysisMap()
mapOldMaskToCurrent = { ...
'Trace Boundaries', ...
   'Trace Boundaries', ...
   'S-Function', ...
   'vipanalysis/Trace Boundaries', ...
   { ...
      'conn'; ...
      'searchDir4'; ...
      'searchDir8'; ...
      'traceDir'; ...
      'maxNumPix'; ...
      'outputNum'; ...
      'fillChoices'; ...
      'fillVal'; ...
   }, ...
   'sviptraceboundary'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visionanalysisMap()
mapOldMaskToCurrent = { ...
'Block Matching', ...
   'Block Matching', ...
   'SubSystem', ...
   'visionanalysis/Block Matching', ...
   { ...
      'which2img'; ...
      'N'; ...
      'searchMethod'; ...
      'blockSize'; ...
      'overlapping'; ...
      'maxDisplacement'; ...
      'matchCriteria'; ...
      'outVelForm'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   ''; ...
'Contrast Adjustment', ...
   'Contrast Adjustment', ...
   'S-Function', ...
   'visionanalysis/Contrast Adjustment', ...
   { ...
      'methodInputRange'; ...
      'rangeIn'; ...
      'fracSaturate'; ...
      'isBinNum'; ...
      'binNum'; ...
      'methodOutputRange'; ...
      'rangeOut'; ...
      'prod1Mode'; ...
      'prod1WordLength'; ...
      'prod1FracLength'; ...
      'prod2Mode'; ...
      'prod2WordLength'; ...
      'prod2FracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipcontrastadjust'; ...
'Corner Detection', ...
   'Corner Detection', ...
   'SubSystem', ...
   'visionanalysis/Corner Detection', ...
   { ...
      'method'; ...
      'factor'; ...
      'filter'; ...
      'thrInten'; ...
      'thrAngle'; ...
      'output'; ...
      'outputInUse'; ...
      'maxNum'; ...
      'thrMetric'; ...
      'neighborSize'; ...
      'isOutVarDim'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'memoryMode'; ...
      'memoryWordLength'; ...
      'memoryFracLength'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   ''; ...
'Deinterlacing', ...
   'Deinterlacing', ...
   'S-Function', ...
   'visionanalysis/Deinterlacing', ...
   { ...
      'method'; ...
      'isInputTransposed'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipdeinterlace'; ...
'Edge Detection', ...
   'Edge Detection', ...
   'S-Function', ...
   'visionanalysis/Edge Detection', ...
   { ...
      'method'; ...
      'outputType'; ...
      'userDefinedThreshold'; ...
      'thresholdSource'; ...
      'threshold'; ...
      'thresholdTuning'; ...
      'edgeThinning'; ...
      'threshold_canny'; ...
      'autoPercent'; ...
      'sigma'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipedge'; ...
'Histogram Equalization', ...
   'Histogram Equalization', ...
   'S-Function', ...
   'visionanalysis/Histogram\nEqualization', ...
   { ...
      'specify'; ...
      'numbins'; ...
      'src'; ...
      'hist'; ...
   }, ...
   'sviphisteq'; ...
'Median Filter', ...
   'Median Filter', ...
   'S-Function', ...
   'visionanalysis/Median Filter', ...
   { ...
      'nghbood'; ...
      'outSize'; ...
      'padType'; ...
      'padSrc'; ...
      'padVal'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipmdnfilter'; ...
'Optical Flow', ...
   'Optical Flow', ...
   'SubSystem', ...
   'visionanalysis/Optical Flow', ...
   { ...
      'method'; ...
      'gradMethod'; ...
      'which2img'; ...
      'N'; ...
      'outVelForm'; ...
      'lambda'; ...
      'stop_criteria'; ...
      'maxAllowAbsDiff'; ...
      'maxIter'; ...
      'numInports'; ...
      'sigmaS'; ...
      'sigmaW'; ...
      'eigTh'; ...
      'discardNormalFlow'; ...
      'outputCurrentImage'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'memoryMode'; ...
      'memoryWordLength'; ...
      'memoryFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   ''; ...
 'Template Matching', ...
   'Template Matching', ...
   'S-Function', ...
   'visionanalysis/Template Matching', ...
   { ...
      'metric'; ...
      'roi'; ...
      'roiValid'; ...
      'output'; ...
      'nMetric'; ...
      'nSize'; ...
      'method'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'sviptemplatematching'; ...
'Trace Boundary', ...
   'Trace Boundary', ...
   'S-Function', ...
   'visionanalysis/Trace Boundary', ...
   { ...
      'conn'; ...
      'searchDir4'; ...
      'searchDir8'; ...
      'traceDir'; ...
      'maxNumPix'; ...
      'outputNum'; ...
      'fillChoices'; ...
      'fillVal'; ...
   }, ...
   'sviptraceboundary'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visionsourcesMap()
mapOldMaskToCurrent = { ...
'Image From File', ...
   'Image From File', ...
   'SubSystem', ...
   'visionsources/Image From File', ...
   { ...
      'FileName'; ...
      'imagePorts'; ...
      'Ts'; ...
      'ImageDataType'; ...
      'Signed'; ...
      'WordLength'; ...
      'sdImageDataType'; ...
      'FractionLengthMode'; ...
      'FractionLength'; ...
      'OutPortLabels'; ...
   }, ...
   ''; ...
'Image From Workspace', ...
   'Image From Workspace', ...
   'SubSystem', ...
   'visionsources/Image From Workspace', ...
   { ...
      'ImageValue'; ...
      'Ts'; ...
      'imagePorts'; ...
      'ImageDataType'; ...
      'Signed'; ...
      'WordLength'; ...
      'sdImageDataType'; ...
      'FractionLengthMode'; ...
      'FractionLength'; ...
      'OutPortLabels'; ...
   }, ...
   ''; ...
'Read Binary File', ...
   'Read Binary File', ...
   'S-Function', ...
   'visionsources/Read Binary File', ...
   { ...
      'FileName'; ...
      'loopOrNot'; ...
      'numLoops'; ...
      'VideoFormat'; ...
      'FOURCC'; ...
      'BitStreamFormat'; ...
      'NumOutputs'; ...
      'ComponentOrder'; ...
      'Interlaced'; ...
      'LineOrdering'; ...
      'Ts'; ...
      'Component1'; ...
      'Component2'; ...
      'Component3'; ...
      'Component4'; ...
      'Bits1'; ...
      'Bits2'; ...
      'Bits3'; ...
      'Bits4'; ...
      'Rows1'; ...
      'Rows2'; ...
      'Rows3'; ...
      'Rows4'; ...
      'Cols1'; ...
      'Cols2'; ...
      'Cols3'; ...
      'Cols4'; ...
      'YRows'; ...
      'YCols'; ...
      'SignedOutput'; ...
      'FileEndian'; ...
      'OutputEOF'; ...
   }, ...
   'svipfileread'; ...
'Video From Workspace', ...
   'Video From Workspace', ...
   'S-Function', ...
   'visionsources/Video From Workspace', ...
   { ...
      'signal'; ...
      'Ts'; ...
      'finalout'; ...
      'finaloutActive'; ...
      'imagePorts'; ...
      'OutPortLabels'; ...
   }, ...
   'svipvideofromwks'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visionutilitiesMap()
mapOldMaskToCurrent = { ...
'Block Processing', ...
   'Block Processing', ...
   'SubSystem', ...
   'visionutilities/Block Processing', ...
   { ...
      'NumI'; ...
      'NumO'; ...
      'Blocksize'; ...
      'Overlapsize'; ...
      'Traverse'; ...
   }, ...
   ''; ...
'Image Pad', ...
   'Image Pad', ...
   'S-Function', ...
   'visionutilities/Image Pad', ...
   { ...
      'method'; ...
      'valSrc'; ...
      'value'; ...
      'spec'; ...
      'rowDirection'; ...
      'outRowsMode'; ...
      'rowSize'; ...
      'outColSize'; ...
      'colDirection'; ...
      'outColsMode'; ...
      'colSize'; ...
      'outRowSize'; ...
      'trunc_flag'; ...
   }, ...
   'sdsppad'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visionconversionsMap()
mapOldMaskToCurrent = { ...
'Autothreshold', ...
   'Autothreshold', ...
   'S-Function', ...
   'visionconversions/Autothreshold', ...
   { ...
      'operator'; ...
      'threshOut'; ...
      'effMetricOut'; ...
      'userDefinedRange'; ...
      'umin'; ...
      'umax'; ...
      'outOfRngOpt'; ...
      'scaleThreshold'; ...
      'scaleFactor'; ...
      'P1Mode'; ...
      'P1WordLength'; ...
      'P1FracLength'; ...
      'A1Mode'; ...
      'A1WordLength'; ...
      'A1FracLength'; ...
      'P2Mode'; ...
      'P2WordLength'; ...
      'P2FracLength'; ...
      'A2Mode'; ...
      'A2WordLength'; ...
      'A2FracLength'; ...
      'P3Mode'; ...
      'P3WordLength'; ...
      'P3FracLength'; ...
      'A3Mode'; ...
      'A3WordLength'; ...
      'A3FracLength'; ...
      'P4Mode'; ...
      'P4WordLength'; ...
      'P4FracLength'; ...
      'A4Mode'; ...
      'A4WordLength'; ...
      'A4FracLength'; ...
      'Q1Mode'; ...
      'Q1WordLength'; ...
      'Q1FracLength'; ...
      'EMMode'; ...
      'EMWordLength'; ...
      'EMFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipgraythresh'; ...
'Chroma Resampling', ...
   'Chroma Resampling', ...
   'S-Function', ...
   'visionconversions/Chroma\nResampling', ...
   { ...
      'resampling'; ...
      'interpolation'; ...
      'antialiasing'; ...
      'hcoeff'; ...
      'vcoeff'; ...
      'isInputTransposed'; ...
   }, ...
   'svipchromresamp'; ...
'Color Space Conversion', ...
   'Color Space Conversion', ...
   'S-Function', ...
   'visionconversions/Color Space\n Conversion', ...
   { ...
      'conversion'; ...
      'conversionActive'; ...
      'wp_str'; ...
      'rec'; ...
      'sys'; ...
      'imagePorts'; ...
   }, ...
   'svipcolorconv'; ...
'Demosaic', ...
   'Demosaic', ...
   'S-Function', ...
   'visionconversions/Demosaic', ...
   { ...
      'algorithm'; ...
      'algorithmActive'; ...
      'alignment'; ...
      'imagePorts'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipdemosaic'; ...
'Gamma Correction', ...
   'Gamma Correction', ...
   'S-Function', ...
   'visionconversions/Gamma Correction', ...
   { ...
      'operation'; ...
      'gamma'; ...
      'linearSegment'; ...
      'breakPoint'; ...
   }, ...
   'svipgamma'; ...
'Image Complement', ...
   'Image Complement', ...
   'S-Function', ...
   'visionconversions/Image Complement', ...
   { ...
   }, ...
   'svipimgcomplement'; ...
'Image Data Type Conversion', ...
   'Image Data Type Conversion', ...
   'S-Function', ...
   'visionconversions/Image Data Type\nConversion', ...
   { ...
      'outDT'; ...
      'isSigned'; ...
      'wordLen'; ...
      'numFracBits'; ...
   }, ...
   'svipscalenconvert'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visiongeotformsMap()
mapOldMaskToCurrent = { ...
'Projective transformation', ...
   'Projective transformation', ...
   'S-Function', ...
   'visiongeotforms/Projective\nTransformation', ...
   { ...
      'inType'; ...
      'imagePorts'; ...
      'mode'; ...
      'inVerticesSrc'; ...
      'inVertices'; ...
      'outVerticesSrc'; ...
      'outVertices'; ...
      'inRectFull'; ...
      'rectSizeSrc'; ...
      'rectSize'; ...
      'inPtsInvalid'; ...
      'outSize'; ...
      'outROI'; ...
      'method'; ...
      'factor'; ...
      'fillVal'; ...
      'interpolation'; ...
      'inVerticesValid'; ...
      'outVerticesValid'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'P1Mode'; ...
      'P1WordLength'; ...
      'P1FracLength'; ...
      'A1Mode'; ...
      'A1WordLength'; ...
      'A1FracLength'; ...
      'P2Mode'; ...
      'P2WordLength'; ...
      'P2FracLength'; ...
      'A2Mode'; ...
      'A2WordLength'; ...
      'A2FracLength'; ...
      'P3Mode'; ...
      'P3WordLength'; ...
      'P3FracLength'; ...
      'A3Mode'; ...
      'A3WordLength'; ...
      'A3FracLength'; ...
      'MatrixMode'; ...
      'MatrixWordLength'; ...
      'MatrixFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipprojective'; ...
'Resize', ...
   'Resize', ...
   'S-Function', ...
   'visiongeotforms/Resize', ...
   { ...
      'specify'; ...
      'rfactor'; ...
      'outCols'; ...
      'outRows'; ...
      'outRowsCols'; ...
      'interp_method'; ...
      'antialias'; ...
      'useROI'; ...
      'roiFlag'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipresize'; ...
'Rotate', ...
   'Rotate', ...
   'S-Function', ...
   'visiongeotforms/Rotate', ...
   { ...
      'outSizeR'; ...
      'src_angle'; ...
      'unit_angle'; ...
      'angle'; ...
      'maxAngle'; ...
      'dispImage'; ...
      'method'; ...
      'fillVal'; ...
      'interpMethod'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'sviprotate'; ...
'Shear', ...
   'Shear', ...
   'S-Function', ...
   'visiongeotforms/Shear', ...
   { ...
      'direction'; ...
      'outSizeS'; ...
      'src_shear'; ...
      'shear_values'; ...
      'maxShear'; ...
      'fillVal'; ...
      'interpMethod'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipshear'; ...
'Translate', ...
   'Translate', ...
   'S-Function', ...
   'visiongeotforms/Translate', ...
   { ...
      'outSizeT'; ...
      'src_trans'; ...
      'translation'; ...
      'maxOffset'; ...
      'fillVal'; ...
      'interpMethod'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'sviptranslate'; ...
'Estimate Geometric Transformation', ...
   'Estimate Geometric Transformation', ...
   'S-Function', ...
   'visiongeotforms/Estimate Geometric\nTransformation', ...
   { ...
      'tformType'; ...
      'isRandomSampling'; ...
      'algMethod'; ...
      'numMethod'; ...
      'isStopSampling'; ...
      'percentStop'; ...
      'distanceAlg'; ...
      'distanceGeo'; ...
      'sampleNum'; ...
      'maxSampleNum'; ...
      'desiredConfidence'; ...
      'isRefineTForm'; ...
      'isOutputInlier'; ...
      'outDT4IntInput'; ...
      'isReleaseMode'; ...
   }, ...
   'svipesttform'; ...
'Apply Geometric Transformation', ...
   'Apply Geometric Transformation', ...
   'S-Function', ...
   'visiongeotforms/Apply Geometric\nTransformation', ...
   { ...
      'tformSource'; ...
      'tformValue'; ...
      'approxProjectiveFlag'; ...
      'errorTolerance'; ...
      'roiMethod'; ...
      'roiSource'; ...
      'roiBBox'; ...
      'roiVertice'; ...
      'inputClipFlag'; ...
      'interpolationMethod'; ...
      'fillValue'; ...
      'viewPortMethod'; ...
      'outputSize'; ...
      'outputLoc'; ...
      'outputClipFlag'; ...
   }, ...
   'svipapplygeotform'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visionmorphopsMap()
mapOldMaskToCurrent = { ...
'Bottom-hat', ...
   'Bottom-hat', ...
   'SubSystem', ...
   'visionmorphops/Bottom-hat', ...
   { ...
      'imgtype'; ...
      'nhoodsrc'; ...
      'strel'; ...
   }, ...
   ''; ...
'Closing', ...
   'Closing', ...
   'S-Function', ...
   'visionmorphops/Closing', ...
   { ...
      'nhoodsrc'; ...
      'strel'; ...
   }, ...
   'svipmorphop'; ...
'Dilation', ...
   'Dilation', ...
   'S-Function', ...
   'visionmorphops/Dilation', ...
   { ...
      'nhoodsrc'; ...
      'strel'; ...
   }, ...
   'svipmorphop'; ...
'Erosion', ...
   'Erosion', ...
   'S-Function', ...
   'visionmorphops/Erosion', ...
   { ...
      'nhoodsrc'; ...
      'strel'; ...
   }, ...
   'svipmorphop'; ...
'Label', ...
   'Label', ...
   'S-Function', ...
   'visionmorphops/Label', ...
   { ...
      'conn'; ...
      'output'; ...
      'outType'; ...
      'lastLabel'; ...
   }, ...
   'sviplabel'; ...
'Opening', ...
   'Opening', ...
   'S-Function', ...
   'visionmorphops/Opening', ...
   { ...
      'nhoodsrc'; ...
      'strel'; ...
   }, ...
   'svipmorphop'; ...
'Top-hat', ...
   'Top-hat', ...
   'SubSystem', ...
   'visionmorphops/Top-hat', ...
   { ...
      'imgtype'; ...
      'nhoodsrc'; ...
      'strel'; ...
   }, ...
   ''; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visionstatisticsMap()
mapOldMaskToCurrent = { ...
'2-D Autocorrelation', ...
   '2-D Autocorrelation', ...
   'S-Function', ...
   'visionstatistics/2-D Autocorrelation', ...
   { ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svip2dconv'; ...
'2-D Correlation', ...
   '2-D Correlation', ...
   'S-Function', ...
   'visionstatistics/2-D Correlation', ...
   { ...
      'outSize'; ...
      'normalize'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svip2dconv'; ...
'2-D Histogram', ...
   '2-D Histogram', ...
   'S-Function', ...
   'visionstatistics/2-D Histogram', ...
   { ...
      'umin'; ...
      'umax'; ...
      'nbins'; ...
      'normalized'; ...
      'run'; ...
      'reset'; ...
      'trigtype'; ...
      'additionalParams'; ...
      'allowOverrides'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'sviphist'; ...
'2-D Mean', ...
   '2-D Mean', ...
   'S-Function', ...
   'visionstatistics/2-D Mean', ...
   { ...
    'run'; ...
    'reset_popup'; ...
    'InputProcessing'; ...
    'directionMode'; ...
    'dimension'; ...
    'treatSBRowAsCol'; ...
    'roiEnable'; ...
    'roiType'; ...
    'roiPortion'; ...
    'roiOutput'; ...
    'roiFlag'; ...
    'additionalParams'; ...
    'allowOverrides'; ...
    'outputMode'; ...
    'outputWordLength'; ...
    'outputFracLength'; ...
    'outputDataTypeStr'; ...
    'outputLastDataTypeStr'; ...
    'outputMin'; ...
    'outputMax'; ...
    'accumMode'; ...
    'accumWordLength'; ...
    'accumFracLength'; ...
    'accumDataTypeStr'; ...
    'accumLastDataTypeStr'; ...
    'roundingMode'; ...
    'overflowMode'; ...
    'LockScale'; ...
   }, ...
   'svipstatfcns'; ...
'2-D Median', ...
   '2-D Median', ...
   'S-Function', ...
   'visionstatistics/2-D Median', ...
   { ...
      'sortAlg'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipmdn'; ...
'2-D Standard Deviation', ...
   '2-D Standard Deviation', ...
   'S-Function', ...
   'visionstatistics/2-D Standard\nDeviation', ...
   { ...
    'run'; ...
    'reset_popup'; ...
    'InputProcessing'; ...
    'directionMode'; ...
    'dimension'; ...
    'treatSBRowAsCol'; ...
    'roiEnable'; ...
    'roiType'; ...
    'roiPortion'; ...
    'roiOutput'; ...
    'roiFlag'; ...
   }, ...
   'svipstatfcns'; ...
'2-D Variance', ...
   '2-D Variance', ...
   'S-Function', ...
   'visionstatistics/2-D Variance', ...
   { ...
    'run'; ...
    'reset_popup'; ...
    'InputProcessing'; ...
    'directionMode'; ...
    'dimension'; ...
    'treatSBRowAsCol'; ...
    'roiEnable'; ...
    'roiType'; ...
    'roiPortion'; ...
    'roiOutput'; ...
    'roiFlag'; ...
    'additionalParams'; ...
    'allowOverrides'; ...
    'outputMode'; ...
    'outputWordLength'; ...
    'outputFracLength'; ...
    'accumMode'; ...
    'accumWordLength'; ...
    'accumFracLength'; ...
    'prodOutputMode'; ...
    'prodOutputWordLength'; ...
    'prodOutputFracLength'; ...
    'memoryMode'; ...
    'memoryWordLength'; ...
    'memoryFracLength'; ...
    'roundingMode'; ...
    'overflowMode'; ...
    'LockScale'; ...
   }, ...
   'svipstatfcns'; ...
'Blob Analysis', ...
   'Blob Analysis', ...
   'S-Function', ...
   'visionstatistics/Blob Analysis', ...
   { ...
      'area'; ...
      'centroid'; ...
      'bBox'; ...
      'majorAxis'; ...
      'minorAxis'; ...
      'angle'; ...
      'eccentricity'; ...
      'equivDiameterSq'; ...
      'extent'; ...
      'perimeter'; ...
      'maxBlobs'; ...
      'warnIfNumBlobsExceeded'; ...
      'isCount'; ...
      'useMinArea'; ...
      'minArea'; ...
      'useMaxArea'; ...
      'maxArea'; ...
      'excludeBorderBlob'; ...
      'outDT'; ...
      'isOutVarDim'; ...
      'isFill'; ...
      'fillValues'; ...
      'conn'; ...
      'isLabel'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'memoryMode'; ...
      'memoryWordLength'; ...
      'memoryFracLength'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'secondCoeffMode'; ...
      'secondCoeffWordLength'; ...
      'secondCoeffFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipblob'; ...
'Find Local Maxima', ...
   'Find Local Maxima', ...
   'S-Function', ...
   'visionstatistics/Find Local Maxima', ...
   { ...
      'num_peaks'; ...
      'nhood_size'; ...
      'src_thresh'; ...
      'src_thresh_inuse'; ...
      'threshold'; ...
      'inputIsHough'; ...
      'dt_peak'; ...
      'dt_count'; ...
      'isOutVarDim'; ...
   }, ...
   'svipfindlocalmax'; ...
'2-D Maximum', ...
   '2-D Maximum', ...
   'S-Function', ...
   'visionstatistics/2-D Maximum', ...
   { ...
    'fcn'; ...
    'reset'; ...
    'InputProcessing'; ...
    'indexBase'; ...
    'operateOver'; ...
    'Dimension'; ...
    'operation'; ...
    'roiEnable'; ...
    'roiType'; ...
    'roiPortion'; ...
    'roiOutput'; ...
    'roiFlag'; ...
    'additionalParams'; ...
    'allowOverrides'; ...
    'accumMode'; ...
    'accumWordLength'; ...
    'accumFracLength'; ...
    'accumDataTypeStr'; ...
    'accumLastDataTypeStr'; ...
    'prodOutputMode'; ...
    'prodOutputWordLength'; ...
    'prodOutputFracLength'; ...
    'prodOutputDataTypeStr'; ...
    'prodOutputLastDataTypeStr'; ...
    'roundingMode'; ...
    'overflowMode'; ...
    'LockScale'; ...
   }, ...
   'svipstatminmax'; ...
'2-D Minimum', ...
   '2-D Minimum', ...
   'S-Function', ...
   'visionstatistics/2-D Minimum', ...
   { ...
    'fcn'; ...
    'reset'; ...
    'InputProcessing'; ...
    'indexBase'; ...
    'operateOver'; ...
    'Dimension'; ...
    'operation'; ...
    'roiEnable'; ...
    'roiType'; ...
    'roiPortion'; ...
    'roiOutput'; ...
    'roiFlag'; ...
    'additionalParams'; ...
    'allowOverrides'; ...
    'accumMode'; ...
    'accumWordLength'; ...
    'accumFracLength'; ...
    'accumDataTypeStr'; ...
    'accumLastDataTypeStr'; ...
    'prodOutputMode'; ...
    'prodOutputWordLength'; ...
    'prodOutputFracLength'; ...
    'prodOutputDataTypeStr'; ...
    'prodOutputLastDataTypeStr'; ...
    'roundingMode'; ...
    'overflowMode'; ...
    'LockScale'; ...
   }, ...
   'svipstatminmax'; ...
'PSNR', ...
   'PSNR', ...
   'S-Function', ...
   'visionstatistics/PSNR', ...
   { ...
   }, ...
   'svippsnr'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visionfilterMap()
mapOldMaskToCurrent = { ...
'2-D Convolution', ...
   '2-D Convolution', ...
   'S-Function', ...
   'visionfilter/2-D Convolution', ...
   { ...
      'outSize'; ...
      'normalize'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svip2dconv'; ...
'2-D FIR Filter', ...
   '2-D FIR Filter', ...
   'S-Function', ...
   'visionfilter/2-D FIR Filter', ...
   { ...
      'separable'; ...
      'filtSrc'; ...
      'filterMtrx'; ...
      'verticalFilter'; ...
      'horizontalFilter'; ...
      'outSize'; ...
      'padType'; ...
      'padSrc'; ...
      'padVal'; ...
      'method'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svip2dfirfilter'; ...
'Median Filter', ...
   'Median Filter', ...
   'S-Function', ...
   'visionfilter/Median Filter', ...
   { ...
      'nghbood'; ...
      'outSize'; ...
      'padType'; ...
      'padSrc'; ...
      'padVal'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipmdnfilter'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visiontextngfixMap()
mapOldMaskToCurrent = { ...
'Compositing', ...
   'Compositing', ...
   'S-Function', ...
   'visiontextngfix/Compositing', ...
   { ...
      'operation'; ...
      'bFacSrc'; ...
      'mFacSrc'; ...
      'bFactor'; ...
      'mFactor'; ...
      'source'; ...
      'coordinates'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipcomposite'; ...
'Draw Markers', ...
   'Draw Markers', ...
   'S-Function', ...
   'visiontextngfix/Draw Markers', ...
   { ...
      'shape'; ...
      'size'; ...
      'fill'; ...
      'fillClrSource'; ...
      'display'; ...
      'intensity'; ...
      'color'; ...
      'opacity'; ...
      'viewport'; ...
      'antialiasing'; ...
      'inType'; ...
      'imagePorts'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'memoryMode'; ...
      'memoryWordLength'; ...
      'memoryFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipdrawmarkers'; ...
'Draw Shapes', ...
   'Draw Shapes', ...
   'S-Function', ...
   'visiontextngfix/Draw Shapes', ...
   { ...
      'shape'; ...
      'fill'; ...
      'lineWidth'; ...
      'fillClrSource'; ...
      'display'; ...
      'intensity'; ...
      'color'; ...
      'opacity'; ...
      'viewport'; ...
      'antialiasing'; ...
      'inType'; ...
      'imagePorts'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'memoryMode'; ...
      'memoryWordLength'; ...
      'memoryFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svipdrawshapes'; ...
'Insert Text', ...
   'Insert Text', ...
   'S-Function', ...
   'visiontextngfix/Insert Text', ...
   { ...
      'inputType'; ...
      'theText'; ...
      'fontFace'; ...
      'dummyVar1'; ...
      'blockFontSize'; ...
      'antiAliased'; ...
      'getTextLocFrom'; ...
      'textLoc'; ...
      'getTextColorFrom'; ...
      'textColor'; ...
      'getTextIntensityFrom'; ...
      'textIntensity'; ...
      'getTextOpacityFrom'; ...
      'textOpacity'; ...
      'dummyVar2'; ...
      'dummyVar3'; ...
      'dummyVar4'; ...
      'imagePorts'; ...
      'isInputTransposed'; ...
   }, ...
   'sviptextrender'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visionsinksMap()
mapOldMaskToCurrent = { ...
'Frame Rate Display', ...
   'Frame Rate Display', ...
   'M-S-Function', ...
   'visionsinks/Frame Rate\nDisplay', ...
   { ...
      'UpdateRate'; ...
   }, ...
   'svipfps'; ...
'To Video Display', ...
   'To Video Display', ...
   'S-Function', ...
   'visionsinks/To Video Display', ...
   { ...
      'inputType'; ...
      'imagePorts'; ...
      'OutputDevice'; ...
      'fullScreen'; ...
      'videoWindowX'; ...
      'videoWindowY'; ...
      'saveWindowSize'; ...
      'videoWindowWidth'; ...
      'videoWindowHeight'; ...
      'dataOrg'; ...
   }, ...
   'svipwvo2'; ...
'Video To Workspace', ...
   'Video To Workspace', ...
   'S-Function', ...
   'visionsinks/Video To Workspace', ...
   { ...
      'VariableName'; ...
      'NumInputs'; ...
      'DataLimit'; ...
      'DecimationFactor'; ...
      'LogFi'; ...
      'InPortLabels'; ...
   }, ...
   'svipvideotowks'; ...
'Video Viewer', ...
   'Video Viewer', ...
   '', ...
   'visionsinks/Video Viewer', ...
   { ...
      'inputType'; ...
      'imagePorts'; ...
      'useColorMap'; ...
      'colormapValue'; ...
      'specRange'; ...
      'minInputVal'; ...
      'maxInputVal'; ...
      'FigPos'; ...
      'AxisZoom'; ...
      'trueSizedOnce'; ...
   }, ...
   ''; ...
'Write Binary File', ...
   'Write Binary File', ...
   'S-Function', ...
   'visionsinks/Write Binary File', ...
   { ...
      'FileName'; ...
      'VideoFormat'; ...
      'FOURCC'; ...
      'BitStreamFormat'; ...
      'NumInputs'; ...
      'ComponentOrder'; ...
      'Interlaced'; ...
      'LineOrdering'; ...
      'InheritBits'; ...
      'Component1'; ...
      'Component2'; ...
      'Component3'; ...
      'Component4'; ...
      'Bits1'; ...
      'Bits2'; ...
      'Bits3'; ...
      'Bits4'; ...
      'SignedInput'; ...
      'FileEndian'; ...
   }, ...
   'svipfilewrite'; ...
};

%--------------------------------------------------------------------------
function mapOldMaskToCurrent = visiontransformsMap()
mapOldMaskToCurrent = { ...
'2-D DCT', ...
   '2-D DCT', ...
   'S-Function', ...
   'visiontransforms/2-D DCT', ...
   { ...
      'CompMethod'; ...
      'TableOpt'; ...
      'BitRevOrder'; ...
      'SkipNorm'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svip2ddct'; ...
'2-D FFT', ...
   '2-D FFT', ...
   'S-Function', ...
   'visiontransforms/2-D FFT', ...
   { ...
      'TableOpt'; ...
      'BitRevOrder'; ...
      'SkipNorm'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'sdspfft2'; ...
'2-D IDCT', ...
   '2-D IDCT', ...
   'S-Function', ...
   'visiontransforms/2-D IDCT', ...
   { ...
      'CompMethod'; ...
      'TableOpt'; ...
      'BitRevOrder'; ...
      'SkipNorm'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svip2ddct'; ...
'2-D IFFT', ...
   '2-D IFFT', ...
   'SubSystem', ...
   'visiontransforms/2-D IFFT', ...
   { ...
      'TableOpt'; ...
      'BitRevOrder'; ...
      'cs_in'; ...
      'SkipNorm'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   ''; ...
'Gaussian Pyramid', ...
   'Gaussian Pyramid', ...
   'S-Function', ...
   'visiontransforms/Gaussian\nPyramid', ...
   { ...
      'operation'; ...
      'level'; ...
      'source'; ...
      'a'; ...
      'coef'; ...
      'hiddenCoef'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'svippyramid'; ...
'Hough Lines', ...
   'Hough Lines', ...
   'S-Function', ...
   'visiontransforms/Hough Lines', ...
   { ...
      'sineCompMethod'; ...
      'thetaRes'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'sviphoughlines'; ...
'Hough Transform', ...
   'Hough Transform', ...
   'S-Function', ...
   'visiontransforms/Hough Transform', ...
   { ...
      'theta_res'; ...
      'rho_res'; ...
      'out_theta_rho'; ...
      'outdtmode'; ...
      'firstCoeffMode'; ...
      'firstCoeffWordLength'; ...
      'firstCoeffFracLength'; ...
      'secondCoeffMode'; ...
      'secondCoeffWordLength'; ...
      'secondCoeffFracLength'; ...
      'outputMode'; ...
      'outputWordLength'; ...
      'outputFracLength'; ...
      'accumMode'; ...
      'accumWordLength'; ...
      'accumFracLength'; ...
      'prodOutputMode'; ...
      'prodOutputWordLength'; ...
      'prodOutputFracLength'; ...
      'memoryMode'; ...
      'memoryWordLength'; ...
      'memoryFracLength'; ...
      'roundingMode'; ...
      'overflowMode'; ...
      'LockScale'; ...
   }, ...
   'sviphough'; ...
};
